### PR TITLE
audio: (fix) AVAudioSession not initialized + improve README

### PR DESCRIPTION
**Pull request by VinceOPS**
Hi guys,

Regarding this issue https://github.com/Taracque/ionic-plugin-callkit/issues/9, I tried to find a workaround and saw in the documentation of [CallKit ](https://developer.apple.com/reference/callkit) that the AVAudioSession had to be initialized by the app. So I added this piece of code, which fixed the issue in my app.

By the way, I improved a few things in the README file.

Thanks for your work @Taracque! I hope it will help.

Regards

### CODE REVIEW

**Comment by manur** [comment]
This PR fixes my app as well. 
Thank you @VinceOPS a ton for this, and @Taracque for writing the original.

**Comment by VinceOPS** [comment]
@manur Glad to read this! 
Btw I'll be interested by a discussion about WebRTC on Cordova, if you got something working. I'm pretty close to release a beta version of my videocall feature (in an already published application), thanks to AppRTC, the "iosrtc" plugin, and the Taracque's callkit + pushkit plugins. Did you use a specific framework/plugin? Thanks :).

**Comment by manur** [comment]
@VinceOPS -- cordova-plugin-iosrtc works pretty well for us for audio. Happy to answer any other questions you may have.

**Comment by Taracque** [comment]
I'm using OpenTok (https://github.com/Taracque/cordova-plugin-opentok) works pretty well for both audio and video, but that is a paid solution.

**Pull request merged**
